DROP TABLE IF EXISTS requests;
DROP TABLE IF EXISTS compilation_events;
DROP TABLE IF EXISTS comments;
DROP TABLE IF EXISTS events;
DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS compilations;

CREATE TABLE IF NOT EXISTS categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(50) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(250) NOT NULL,
    email VARCHAR(254) NOT NULL,
    CONSTRAINT uq_users_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    annotation TEXT NOT NULL,
    category_id BIGINT NOT NULL,
    conf_req INTEGER,
    created TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    description TEXT NOT NULL,
    event_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    initiator_id INTEGER NOT NULL,
    location_lat DOUBLE PRECISION,
    location_lon DOUBLE PRECISION,
    paid BOOLEAN NOT NULL,
    participant_limit INTEGER,
    published TIMESTAMP WITHOUT TIME ZONE,
    request_moderation BOOLEAN,
    status varchar(30),
    title varchar(120) NOT NULL,
    FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE CASCADE,
    FOREIGN KEY (initiator_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT,
    created TIMESTAMP WITHOUT TIME ZONE,
    requester_id BIGINT,
    status varchar(20),
    FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE CASCADE,
    FOREIGN KEY (requester_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS compilations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pinned BOOLEAN,
    title varchar(50)
);

CREATE TABLE IF NOT EXISTS compilation_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    compilation_id BIGINT NOT NULL,
    event_id BIGINT NOT NULL,
    FOREIGN KEY (compilation_id) REFERENCES compilations(id) ON DELETE CASCADE,
    FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text TEXT NOT NULL,
    status varchar(30),
    author_name varchar(512),
    created TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated TIMESTAMP WITHOUT TIME ZONE,
    moderated TIMESTAMP WITHOUT TIME ZONE,
    event_id BIGINT NOT NULL,
    author_id BIGINT NOT NULL,
    moderator_id BIGINT,
    moderation_reason varchar(512),
    FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE CASCADE,
    FOREIGN KEY (author_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (moderator_id) REFERENCES users(id) ON DELETE CASCADE
);


-- Выполнять после заполнения Postman
--INSERT INTO comments (
--	text,
--	author_name,
--	status,
--	created,
--	updated,
--	event_id,
--	author_id
--)
--VALUES (
--	'Тестовый комментарий 1',
--	' Иванов Иван Иванович',
--	'PENDING',
--	'2026-07-15 14:15:00',
--	'2026-07-16 10:10:00',
--	1,
--	1
--);
--
--INSERT INTO comments (
--	text,
--	author_name,
--	status,
--	created,
--	updated,
--	event_id,
--	author_id
--)
--VALUES (
--	'Другой тестовый комментарий',
--	'Сидов Анатолий Александрович',
--	'PENDING',
--	'2026-07-15 10:15:00',
--	'2026-07-16 09:10:00',
--	1,
--	2
--);

